Add testnets (#4)
* move REGISTRY_ROOT_URL to env vars

* add testnets

* don't tag authors

* soneium-minato

* bump version

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -33,13 +33,19 @@ jobs:
       - name: Generate registry types
         run: bun generate:types
 
-      - name: Validate logic
+      - name: Check env variables
         run: |
+          if [ -z "${{ vars.REGISTRY_ROOT_URL }}" ]; then
+            echo "Error: REGISTRY_ROOT_URL is not set"
+            exit 1
+          fi
           if [ -z "${{ env.THEGRAPH_STUDIO_KEY }}" ]; then
             echo "Error: secrets.THEGRAPH_STUDIO_KEY is not set - can't validate networks"
             exit 1
           fi
-          bun validate:networks
+
+      - name: Validate logic
+        run: bun validate:networks
 
       - name: Generate registry
         run: bun generate:public
@@ -72,9 +78,9 @@ jobs:
         run: |
           PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
           if [ -z "$PREV_TAG" ]; then
-            CHANGELOG=$(git log --pretty=format:"- %s (@%an) [%h](https://github.com/$GITHUB_REPOSITORY/commit/%H)" --no-merges)
+            CHANGELOG=$(git log --pretty=format:"- %s (%an) [%h](https://github.com/$GITHUB_REPOSITORY/commit/%H)" --no-merges)
           else
-            CHANGELOG=$(git log --pretty=format:"- %s (@%an) [%h](https://github.com/$GITHUB_REPOSITORY/commit/%H)" --no-merges ${PREV_TAG}..HEAD)
+            CHANGELOG=$(git log --pretty=format:"- %s (%an) [%h](https://github.com/$GITHUB_REPOSITORY/commit/%H)" --no-merges ${PREV_TAG}..HEAD)
           fi
           echo "CHANGELOG<<EOF" >> $GITHUB_ENV
           echo "$CHANGELOG" >> $GITHUB_ENV
@@ -121,4 +127,4 @@ jobs:
 
     env:
       THEGRAPH_STUDIO_KEY: ${{ secrets.THEGRAPH_STUDIO_KEY }}
-      REGISTRY_ROOT_URL: "https://graphregistry.pages.dev"
+      REGISTRY_ROOT_URL: ${{ vars.REGISTRY_ROOT_URL }}
